let DistrictList=[
    {name: 'Bagerhat', code: 'BD-05'},
    {name: 'Bandarban', code: 'BD-01'},
    {name: 'Barguna', code: 'BD-02'},
    {name: 'Barishal', code: 'BD-06'},
    {name: 'Bhola', code: 'BD-07'},
    {name: 'Bagura', code: 'BD-03'},
    {name: 'Brahmanbaria', code: 'BD-04'},
    {name: 'Chandpur', code: 'BD-09'},
    {name: 'Chapai Nawabganj', code: 'BD-45'},
    {name: 'Chattogram', code: 'BD-10'},
    {name: 'Coxs Bazar', code: 'BD-11'},
    {name: 'Cumilla', code: 'BD-08'},
    {name: 'Dhaka', code: 'BD-13'},
    {name: 'Dinajpur', code: 'BD-14'},
    {name: 'Faridpur', code: 'BD-15'},
    {name: 'Feni', code: 'BD-16'},
    {name: 'Gaibandha', code: 'BD-19'},
    {name: 'Gazipur', code: 'BD-18'},
    {name: 'Gopalganj', code: 'BD-17'},
    {name: 'Habiganj', code: 'BD-20'},
    {name: 'Jamalpur', code: 'BD-21'},
    {name: 'Jashore', code: 'BD-22'},
    {name: 'Jhalakathi', code: 'BD-25'},
    {name: 'Jhenaidah', code: 'BD-23'},
    {name: 'Joypurhat', code: 'BD-24'},
    {name: 'Khagrachhari', code: 'BD-29'},
    {name: 'khulna', code: 'BD-27'},
    {name: 'Kurigram', code: 'BD-28'},
    {name: 'Kushtia', code: 'BD-30'},
    {name: 'Lakshmipur', code: 'BD-31'},
    {name: 'Lalmonirhat', code: 'BD-32'},
    {name: 'Narayanganj', code: 'BD-40'},
    {name: 'Noakhali', code: 'BD-47'},
    {name: 'Pabna', code: 'BD-49'},
    {name: 'Rajshahi', code: 'BD-54'},
    {name: 'Rangamati', code: 'BD-56'},
    {name: 'Rangpur', code: 'BD-55'},
    {name: 'Sylhet', code: 'BD-60'},
    {name: 'Tangail', code: 'BD-63'},
    {name: 'Thakurgaon', code: 'BD-64'},
    
]

export {DistrictList};